name: Release

on:
  push:
    branches:
    - "master"

jobs:
  release:
    container:
      image: node:10-stretch
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - uses: actions/checkout@v1
    - name: apt install git build-essential
      run: apt update && apt install -y git build-essential
    - name: install build dependencies
      run: make dl-tools
    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx --package @semantic-release/exec --package semantic-release semantic-release
